<?php
require 'connection.php';
require '../vendor/autoload.php';

use Mpdf\Mpdf;

session_start();


// Fetch task completion summary per event
try {
    $stmt = $pdo->query("SELECT 
        e.name AS event_name,
        COUNT(t.id) AS total_tasks,
        SUM(t.status = 'Completed') AS completed,
        SUM(t.status = 'In Progress') AS in_progress,
        SUM(t.status = 'Pending') AS pending,
        SUM(t.due_date < NOW() AND t.status != 'Completed') AS overdue
    FROM events e
    JOIN tasks t ON t.event_id = e.event_id
    GROUP BY e.event_id");

    $report = $stmt->fetchAll(PDO::FETCH_ASSOC);
} catch (PDOException $e) {
    die("Error fetching task report: " . $e->getMessage());
}

function getEfficiencyStatus($percentage) {
    if ($percentage >= 90) return ['Excellent', 'success'];
    if ($percentage >= 50) return ['Moderate', 'warning'];
    return ['Poor', 'danger'];
}

// Create mPDF instance
$mpdf = new Mpdf();

$logoPath = '../img/logowhite.png';

$logoPath = __DIR__ . '/../img/logoblack.png';

$logoBase64 = '';
if (file_exists($logoPath)) {
    $logoData = file_get_contents($logoPath);
    $logoBase64 = 'data:image/png;base64,' . base64_encode($logoData);
}

$mpdf->SetHTMLHeader('
    <div style="display: flex; align-items: center; justify-content: space-between; border-bottom: 1px solid #ccc; padding-bottom: 5px;">
        <img src="' . $logoBase64 . '" height="30" style="margin-right: 10px;">
        <span style="font-family: Sacramento, cursive;font-size: 18px; font-weight: bold; text-align: right; flex-grow: 1; color: #FF6D1F;">HiveFlow</span>
    </div>
');

$mpdf->SetMargins(15, 15, 30);


// Footer with timestamp and page number
$mpdf->SetHTMLFooter('
    <div style="text-align: center; font-size: 10px;">
        Generated by HiveFlow System on ' . date("Y-m-d H:i:s") . ' | Page {PAGENO}
    </div>
');


// CSS for table styling
$stylesheet = "
    body { font-family: sans-serif; }
    table { border-collapse: collapse; width: 100%; }
    th, td { border: 1px solid #333; padding: 8px; text-align: center; }
    th { background-color: #f2f2f2; }
    .badge-success { background-color: #28a745; color: white; padding: 4px 8px; border-radius: 5px; }
    .badge-warning { background-color: #ffc107; color: black; padding: 4px 8px; border-radius: 5px; }
    .badge-danger { background-color: #dc3545; color: white; padding: 4px 8px; border-radius: 5px; }
";

$mpdf->WriteHTML($stylesheet, \Mpdf\HTMLParserMode::HEADER_CSS);

// HTML content
$html = '
<h2 style="text-align:center;">Task Completion Report</h2>
<p><strong>Note:</strong> Completion % is based on completed tasks vs total tasks. Efficiency status is color-coded.</p>
<table>
    <thead>
        <tr>
            <th>Event Name</th>
            <th>Total Tasks</th>
            <th>Completed</th>
            <th>In Progress</th>
            <th>Pending</th>
            <th>Overdue</th>
            <th>Completion %</th>
            <th>Status</th>
        </tr>
    </thead>
    <tbody>';

foreach ($report as $row) {
    $completion = $row['total_tasks'] > 0 ? round(($row['completed'] / $row['total_tasks']) * 100, 1) : 0;
    [$efficiency, $badge] = getEfficiencyStatus($completion);
    $html .= '<tr>
        <td>' . htmlspecialchars($row['event_name']) . '</td>
        <td>' . $row['total_tasks'] . '</td>
        <td>' . $row['completed'] . '</td>
        <td>' . $row['in_progress'] . '</td>
        <td>' . $row['pending'] . '</td>
        <td>' . $row['overdue'] . '</td>
        <td>' . $completion . '%</td>
        <td><span class="badge-' . $badge . '">' . $efficiency . '</span></td>
    </tr>';
}

$html .= '</tbody></table>';

// Output PDF to browser
$mpdf->WriteHTML($html);
$mpdf->Output('task_report.pdf', \Mpdf\Output\Destination::INLINE); // Change to DOWNLOAD for force-download